### ISSUE TITLE
Git scrape Product and Group information for all agencies

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/littlepay#18]
We would like to understand changes over time to the Littlepay Product and Group details for each agency we work with. This has come up recently as we learned about a change to a Product ID after that Product was duplicated to create a new Product -- we didn't expect this to create a TWO new Products 🤷 

So we'd like to capture the output of our `littlepay groups` and `littlepay products` CLI commands, in CSV files stored in this repository, to be able to assess those changes over time more easily.

## Acceptance Criteria

- [ ] For each agency in production (MST, SacRT, SBMTD as of opening this issue)
- [ ] On some schedule (at least once per day)
- [ ] Run `littlepay groups` and `littlepay products`
- [ ] Store the data in a corresponding CSV file in this repository: `data/[agency slug]_[groups|products].csv`
- [ ] With column headers matching the fields in the corresponding [`GroupResponse`](https://github.com/cal-itp/littlepay/blob/main/littlepay/api/groups.py#L9) and [`ProductResponse`](https://github.com/cal-itp/littlepay/blob/main/littlepay/api/products.py#L9) objects
- [ ] Also store the output of `littlepay groups products` in a CSV file in this repository: `data/[agency slug]_linked_groups_products.csv`
- [ ] With column headers `group_id, product_id`
- [ ] A new commit is made each time this process runs, for each agency, when any data file is changed

## Additional context

Sort of related to the work in https://github.com/cal-itp/benefits/pull/1889, can be implemented in workflow in a similar fashion.

More about the [git scraping technique](https://simonwillison.net/2020/Oct/9/git-scraping/).

**Comment by thekaveman** [comment]
cc @indexing @o-ram, here's the ticket write up for collecting Littlepay Group and Product info over time in this `littlepay` repository.

Question for you both: how frequently and when should this process run?

**Comment by thekaveman** [comment]
Going with once per day in the evening (roughly 10-11pm Pacific) for now -- this will capture any changes made throughout the day, and we'll note the timestamp of when we capture the changes to hopefully make later analysis a little easier.

**Comment by indexing** [comment]
@thekaveman The time and frequency sound good to me; seems like a good match for the infrequnecy with which products change.

**Comment by o-ram** [comment]
@thekaveman also sounds good to me!
